name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      env:
        VERSION: ${{ github.event.inputs.version }}
      run: make build

    - name: Docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: make docker-login

    - name: Push edge image
      if: "!github.event.inputs.version"
      run: make docker-push-edge

    - name: Push stable image
      if: github.event.inputs.version
      env:
        VERSION: ${{ github.event.inputs.version }}
      run: make docker-push-stable